# Generated by Django 2.2.16 on 2020-10-21 09:18

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0004_remove_flag_sessions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verifieduser',
            index=models.Index(fields=['feature', 'phone_number'], name='waffle_veri_feature_7538d1_idx'),
        ),
    ]
