# Generated by Django 2.2.16 on 2020-10-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0004_remove_flag_sessions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verifieduser',
            index=models.Index(fields=['feature', 'phone_number'], name='waffle_verifieduser_feature_id_phone_number_86d175dd'),
        ),
    ]
